[package]
name = "task_masker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "^0.11"
bevy_ecs_tilemap = "^0.11"
anyhow = "^1"
tiled = "^0.11"
#bevy-inspector-egui = "^0.19"