[package]
name = "task_masker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "^0.11", features = ["wav", "wayland"] }
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap.git", rev = "55c15bfa43c7a9e2adef6b70007e92d699377454" }
anyhow = "^1"
tiled = "^0.11"
rand = "^0.8"
#bevy-inspector-egui = "^0.19"